webtalk_init -webtalk_dir C:/Users/ZhangFirst1/Desktop/cclab/mips/mips.sim/sim_1/behav/xsim/xsim.dir/mips_min_sopc_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jun 30 20:01:48 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "23491a7d-e04d-4758-9a23-ba4f5b81a460" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b26be5e4c3c2492c9ad6a7f80fdc43f9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "91" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "131 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "9 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "112" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "16" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.51_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "49240_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3856924995 -regid "" -xml C:/Users/ZhangFirst1/Desktop/cclab/mips/mips.sim/sim_1/behav/xsim/xsim.dir/mips_min_sopc_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ZhangFirst1/Desktop/cclab/mips/mips.sim/sim_1/behav/xsim/xsim.dir/mips_min_sopc_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ZhangFirst1/Desktop/cclab/mips/mips.sim/sim_1/behav/xsim/xsim.dir/mips_min_sopc_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
